# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Foodly' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	# add the Firebase pod for Google Analytics
	pod 'Firebase/Analytics'
	pod 'Firebase/Firestore'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'IQKeyboardManagerSwift' 
  pod 'MBProgressHUD', '~> 1.2.0'
  pod 'FirebaseRemoteConfig'
  pod 'Firebase/Crashlytics'

	# or pod ‘Firebase/AnalyticsWithoutAdIdSupport’
	# for Analytics without IDFA collection capability

	# add pods for any other desired Firebase products
	# https://firebase.google.com/docs/ios/setup#available-pods
  # Pods for Foodly

  target 'FoodlyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FoodlyUITests' do
    # Pods for testing
  end

end
